### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by mattdmem** [sheffield-bioinformatics-core/periscope#1]
I think this is an error related to an amplicon with no coverage?

```
[32:04<16:14:51,  6.26it/s]Traceback (most recent call last):
  File "/home/XX/miniconda2/envs/periscope/lib/python3.6/site-packages/periscope/scripts/search_for_sgRNA.py", line 517, in <module>
    periscope = main(args)
  File "/home/XX/miniconda2/envs/periscope/lib/python3.6/site-packages/periscope/scripts/search_for_sgRNA.py", line 490, in main
    total_counts,orf_bed_object = calculate_normalised_counts(mapped_reads,total_counts,outfile_amplicons,orf_bed_object)
  File "/home/XX/miniconda2/envs/periscope/lib/python3.6/site-packages/periscope/scripts/search_for_sgRNA.py", line 212, in calculate_normalised_counts
    amplicon_orf_sgRPTg = amplicon_orf_sgRNA_count / (amplicon_gRNA_count / 1000)
ZeroDivisionError: float division by zero
```

**Comment by mattdmem** [comment]
As thought this was because an amplicon had no genomic RNA - it's actually ORF1a, probably all reads assigned as subgenomic. Probably in future we need to remove ORF1a from predictions
