### ISSUE TITLE
Error when running search_for_sgRNA_illumina.py

### ISSUE THREAD

**Issue by kjshan** [sheffield-bioinformatics-core/periscope#48]
**I do have any error when I run this command below and obtain the error**
![微信截图_20230215162258](https://user-images.githubusercontent.com/71307882/218973611-55ab2704-33bd-41a7-8dda-462c554b636f.png)

### **command:**
python /lustre/user/lulab/shankj/miniconda3/envs/periscope/lib/python3.6/site-packages/periscope/scripts/search_for_sgRNA_illumina.py --bam MA104_Alpha.bam --score-cutoff 50 --output-prefix MA104_Alpha --score-cutoff 50 --sample MA104_Alpha --orf-bed /gpfs2/shankj/software/periscope-master/periscope/resources//orf_start.bed --primer-bed /gpfs2/shankj/software/periscope-master/periscope/resources/artic_primers_V1.bed --amplicon-bed /gpfs2/shankj/software/periscope-master/periscope/resources/artic_amplicons_V1.bed --tmp /tmp --threads 1

### **Error:**
2023-02-15 15:28:34,158 - staring periscope
  0%|                                                                                                                                                                                               | 0/10 [00:00<?, ?it/s]2023-02-15 15:33:03,688 - Processing 6663791 reads
Process Process-1:
Traceback (most recent call last):
  File "/lustre/user/lulab/shankj/miniconda3/envs/periscope/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/lustre/user/lulab/shankj/miniconda3/envs/periscope/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/lustre/user/lulab/shankj/miniconda3/envs/periscope/lib/python3.6/concurrent/futures/process.py", line 181, in _process_worker
    result=r))
  File "/lustre/user/lulab/shankj/miniconda3/envs/periscope/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/lustre/user/lulab/shankj/miniconda3/envs/periscope/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/lustre/user/lulab/shankj/miniconda3/envs/periscope/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
  0%|                                                                                                                                                                                               | 0/10 [37:39<?, ?it/s]
Traceback (most recent call last):
  File "/lustre/user/lulab/shankj/miniconda3/envs/periscope/lib/python3.6/site-packages/periscope/scripts/search_for_sgRNA_illumina.py", line 393, in <module>
    periscope = main(args)
  File "/lustre/user/lulab/shankj/miniconda3/envs/periscope/lib/python3.6/site-packages/periscope/scripts/search_for_sgRNA_illumina.py", line 309, in main
    workers=int(args.threads)
  File "/lustre/user/lulab/shankj/miniconda3/envs/periscope/lib/python3.6/site-packages/periscope/scripts/search_for_sgRNA_illumina.py", line 281, in multiprocessing
    res = list(tqdm(ex.map(func, args), total=len(args)))
  File "/lustre/user/lulab/shankj/miniconda3/envs/periscope/lib/python3.6/site-packages/tqdm/std.py", line 1129, in __iter__
    for obj in iterable:
  File "/lustre/user/lulab/shankj/miniconda3/envs/periscope/lib/python3.6/concurrent/futures/process.py", line 366, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/lustre/user/lulab/shankj/miniconda3/envs/periscope/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/lustre/user/lulab/shankj/miniconda3/envs/periscope/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/lustre/user/lulab/shankj/miniconda3/envs/periscope/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

**Could you guys be friendly to help me? 
Thanks for your time**

**Comment by mbdabrowska1** [comment]
Hi, could you try using more threads to see if this helps the issue?
