### ISSUE TITLE
pybedtools error - novel sub-genomic at 0

### ISSUE THREAD

**Issue by mattdmem** [sheffield-bioinformatics-core/periscope#6]
```Traceback (most recent call last):
  File "/data/md1mpar/.conda/periscope/lib/python3.6/site-packages/periscope/scripts/search_for_sgRNA.py", line 494, in <module>
    periscope = main(args)
  File "/data/md1mpar/.conda/periscope/lib/python3.6/site-packages/periscope/scripts/search_for_sgRNA.py", line 465, in main
    total_counts,orf_bed_object = calculate_normalised_counts(mapped_reads,total_counts,outfile_amplicons,orf_bed_object)
  File "/data/md1mpar/.conda/periscope/lib/python3.6/site-packages/periscope/scripts/search_for_sgRNA.py", line 251, in calculate_normalised_counts
    orf_bed_object = orf_bed_object.cat(read_feature,postmerge=False)
  File "/data/md1mpar/.conda/periscope/lib/python3.6/site-packages/pybedtools/bedtool.py", line 917, in decorated
    result = method(self, *args, **kwargs)
  File "/data/md1mpar/.conda/periscope/lib/python3.6/site-packages/pybedtools/bedtool.py", line 3235, in cat
    [self.file_type] + [i.file_type for i in other_beds]
  File "/data/md1mpar/.conda/periscope/lib/python3.6/site-packages/pybedtools/bedtool.py", line 3235, in <listcomp>
    [self.file_type] + [i.file_type for i in other_beds]
  File "/data/md1mpar/.conda/periscope/lib/python3.6/site-packages/pybedtools/bedtool.py", line 1125, in file_type
    self._file_type = six.advance_iterator(iter(self)).file_type
  File "pybedtools/cbedtools.pyx", line 792, in pybedtools.cbedtools.IntervalIterator.__next__
  File "pybedtools/cbedtools.pyx", line 698, in pybedtools.cbedtools.create_interval_from_list
pybedtools.cbedtools.MalformedBedLineError: Unable to detect format from ['MN908947.3', '-1', '0', 'novel_0']```

**Comment by mattdmem** [comment]
Added if statement that catches positions of 0
